### ISSUE TITLE
Question about the 'registration_strategy' in input_metadata.yml

### ISSUE THREAD

**Issue by changruizhu96** [ragavsachdeva/CYWS-3D#3]
Hi Ragav,

I am confused about this registration_strategy in input_metadata.yml, 
In the provided input_metadata.yml, the first two testing image pairs are like this:
```
batch:
  # 2x RGB images only (3D scene)
  - image1: "demo_data/ship_0.jpg"
    image2: "demo_data/ship_2.jpg"
    registration_strategy: "3d"
  # 2x RGB images, with GT depth (3D scene)
  - image1: "demo_data/ship_0.jpg"
    image2: "demo_data/ship_2.jpg"
    depth1: "demo_data/depth_ship_0.png"
    depth2: "demo_data/depth_ship_2.png"
    registration_strategy: "3d"
```

When I only kept this and ran the code,  everything was fine. I got two prediction results prediction_0 and prediction_1. Prediction_1 was better than the prediction_0, which makes sense, as there are extra inputs.
However, When I only keep the first image pair:

```
batch:
  # 2x RGB images only (3D scene)
  - image1: "demo_data/ship_0.jpg"
    image2: "demo_data/ship_2.jpg"
    registration_strategy: "3d"
```

And deleted the second image pair. I had an error: 
`Traceback (most recent call last):
  File "/home/changrui/CYWS-3D/inference.py", line 69, in <module>
    CLI(main)
  File "/home/changrui/anaconda3/envs/cyws3d/lib/python3.9/site-packages/jsonargparse/_cli.py", line 96, in CLI
    return _run_component(components, cfg_init)
  File "/home/changrui/anaconda3/envs/cyws3d/lib/python3.9/site-packages/jsonargparse/_cli.py", line 181, in _run_component
    return component(**cfg)
  File "/home/changrui/CYWS-3D/inference.py", line 31, in main
    batch_image1_predicted_bboxes, batch_image2_predicted_bboxes = model.predict(batch)
  File "/home/changrui/anaconda3/envs/cyws3d/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/changrui/CYWS-3D/modules/model.py", line 106, in predict
    image1_outputs, image2_outputs = self(batch)
  File "/home/changrui/anaconda3/envs/cyws3d/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/changrui/CYWS-3D/modules/model.py", line 79, in forward
    image1_encoded_features[i + 1], image2_encoded_features[i + 1] = self.registeration_module(
  File "/home/changrui/anaconda3/envs/cyws3d/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/changrui/CYWS-3D/modules/registeration_module.py", line 176, in forward
    image1_3d, image2_3d, trasform_points_1_to_2_3d, transform_points_2_to_1_3d = self.register_features(slice_batch_given_bool_array(batch, reg_3d), image1[reg_3d], image2[reg_3d], "3d")
  File "/home/changrui/CYWS-3D/modules/registeration_module.py", line 148, in register_features
    image1_warped_onto_image2, image2_warped_onto_image1, trasform_points_1_to_2, transform_points_2_to_1  = self.register_3d_features(
  File "/home/changrui/CYWS-3D/modules/registeration_module.py", line 31, in register_3d_features
    torch.stack([batch["intrinsics1"][i] for i, x in enumerate(using_camera_parameters) if x]),
RuntimeError: stack expects a non-empty TensorList.`
It seems like it lacks some data for registration.
When I changed registration_strategy from 3d to 2d, it worked with no error. I got a new prediction_0, but it looks very similar to the previous prediction_0. 
First, I don't know why a single pair of tests is buggy. Second, why the change from 3d to 2d doesn't seem to change the results.
I don't know why these are happening, and I don't know what these three strategies actually represent. Could you please tell me?
